"""test_turn1_decisions.py — Integration tests for all Turn 1 opening decisions.

Each of the 120 test cases corresponds to one row in the baseline turn1-openings
snapshot (snapshots/turn1_openings/baseline.md, generated by the turn1_openings
scenario for the frozen baseline roster).  Expected values — move name, target
species, and weight — are treated as ground truth.  Any regression in the scoring
pipeline will cause the corresponding test(s) to fail, giving an immediate
reference point for what changed.  (The snapshot's engine version comes from
version.__version__; test_summary_header_matches_version guards that it was
regenerated after a version bump.)

Sections mirror the six lead configurations in the snapshot:
  1. Aerodactyl[A] + Venusaur[B]  (mega: Aerodactyl)
  2. Aerodactyl[A] + Venusaur[B]  (mega: Venusaur)
  3. Garchomp[A]   + Kingambit[B] (no mega)
  4. Aerodactyl[A] + Sneasler[B]  (mega: Aerodactyl)
  5. Garchomp[A]   + Venusaur[B]  (mega: Venusaur)
  6. Sneasler[A]   + Kingambit[B] (no mega)

Run:
    .venv\\Scripts\\pytest tests/test_turn1_decisions.py
"""
from __future__ import annotations

import pytest
from battle import BattleState, Pokemon
from decision.modules import (
    make_engine,
    _partner_can_ohko,
    _opp_neutralized_before_acting,
    _opp_has_attacking_priority,
    _ko_before_acting,
    _PROTECT_MOVES,
)
from team import find_member, get_team
import team as _team

# ── Shared engine (stateless — safe to share across all tests) ─────────────────

# Baseline roster bench, base-name form (matches the frozen baseline snapshot).
# For a non-baseline active team, the bench is derived from get_team() instead.
_ALL_TEAM = ["Aerodactyl", "Kingambit", "Sneasler", "Basculegion", "Venusaur", "Garchomp"]
_ENGINE = make_engine()


# ── State / action builders ────────────────────────────────────────────────────

def _our_mon(sp: str) -> Pokemon:
    tm = find_member(sp)
    hp = tm.stats["hp"]
    return Pokemon(
        ident=f"p1: {sp}", species=sp, hp=hp, max_hp=hp,
        ability=tm.ability, item=tm.item, moves=list(tm.moves),
    )


def _opp_mon(sp: str) -> Pokemon:
    return Pokemon(
        ident=f"p2: {sp}", species=sp,
        hp=100, max_hp=100, hp_is_percentage=True,
    )


def _moves(sp: str) -> list[dict]:
    tm = find_member(sp)
    return [{"move": m} for m in tm.moves] if tm else []


def _make_state(our_a: str, our_b: str, opp_a: str, opp_b: str, mega) -> BattleState:
    """Build a fresh Turn-1 BattleState for the given lead/opponent pairing."""
    # Baseline (no active team) uses the frozen base-name roster; a named active
    # team derives its bench from the actual roster (so per-team snapshots work).
    roster = _ALL_TEAM if _team.active_team() is None else [m.name for m in get_team()]
    bench = [s for s in roster if s not in (our_a, our_b)]
    s = BattleState(battle_id="test", my_side="p1")
    s.my_actives         = [_our_mon(our_a),  _our_mon(our_b)]
    s.my_team            = list(s.my_actives)
    s.opp_actives        = [_opp_mon(opp_a),  _opp_mon(opp_b)]
    s.available_switches = [_our_mon(b) for b in bench]
    s.moves_per_slot     = [_moves(our_a), _moves(our_b)]
    s.my_last_moves      = ["", ""]
    s.opp_last_moves     = ["", ""]
    s.my_slot_decisions  = [None, None]
    s.opp_tailwind       = False
    s.opp_tailwind_turns_left = 0
    s.trick_room         = False
    s.trick_room_turns_left  = 0
    s.weather            = None
    s.my_tailwind        = False
    s.my_disabled_moves  = [None, None]
    s.my_encored_moves   = [None, None]
    s.designated_mega    = mega
    return s


def _run(our_a: str, our_b: str, opp_a: str, opp_b: str, mega) -> tuple:
    """Build a Turn-1 BattleState; return (best_a, best_b) Action objects.

    Mirrors main.py's turn flow exactly: phase-1 scores each slot's (move,target)
    candidates in isolation, then DecisionEngine.coordinate picks the best joint
    pair (doubling / overkill / gratuitous-Protect / fake-out / switch-collision
    handled jointly) — so these decisions match actual in-game play.
    """
    s = _make_state(our_a, our_b, opp_a, opp_b, mega)
    chosen, _ = _ENGINE.coordinate(s)
    return chosen[0], chosen[1]


def _chk(action, dec: str, opp_a: str, opp_b: str, wt: float) -> None:
    """Assert that *action* matches a snapshot decision string and weight.

    Decision string formats:
      "MoveName → TargetSpecies"   — attacking move; target_slot is checked
      "MoveName → ?"               — no-target move (any Protect-family move:
                                     Protect/King's Shield/Spiky Shield/…, or a
                                     self/field move); target_slot must be None
      "Switch → BenchSpecies"     — switch action; switch_target is checked
    """
    label, _, target = dec.partition(" → ")
    if label == "Switch":
        assert action.switch_target == target, (
            f"Expected Switch→{target!r}, got Switch→{action.switch_target!r}"
        )
    elif target == "?":
        # No-target move (Protect-family or self/field): the renderer emits "→ ?"
        # whenever target_slot is None.  Check the move name, not a target slot.
        assert action.move_name == label, (
            f"Expected no-target move {label!r}, got {action.move_name!r}"
        )
        assert action.target_slot is None, (
            f"{label!r}: expected no target, got target_slot {action.target_slot}"
        )
    else:
        # Attacking move with a specific target
        assert action.move_name == label, (
            f"Expected move {label!r}, got {action.move_name!r}"
        )
        expected_slot = 0 if target == opp_a else 1
        assert action.target_slot == expected_slot, (
            f"Move {label!r}: expected target_slot {expected_slot} ({target!r}), "
            f"got target_slot {action.target_slot}"
        )
    assert action.weight == pytest.approx(wt, abs=0.05), (
        f"{dec}: expected weight ≈{wt}, got {action.weight:.4f}"
    )


@pytest.fixture(autouse=True)
def _reset_to_baseline_team():
    """Every test runs against the baseline roster unless it selects another.
    The snapshot-cell test picks a team per row; this resets afterward so the
    targeted engine guards below always see the baseline."""
    _team.set_active_team(None)
    yield
    _team.set_active_team(None)


# ═══════════════════════════════════════════════════════════════════════════════
# Speed-awareness regression guards (bug fix + turn-order awareness)
# ═══════════════════════════════════════════════════════════════════════════════

def test_partner_can_ohko_respects_percentage_hp():
    """A ~97%-avg hit on a full-HP opponent is NOT a guaranteed OHKO.

    Opponents are tracked at percentage HP with a placeholder ``max_hp`` (100).
    ``_partner_can_ohko`` must treat that as 'unknown' so the damage layer uses
    typical-spread HP — not read the percentage as 100 absolute HP, which made
    every mid-power hit look like a guaranteed OHKO (the bug behind case 4.6).

    Mega Aerodactyl's best single move vs a healthy opposing Aerodactyl is Rock
    Tomb at ~97% average (min roll < 100%), so this must be False.
    """
    s = _make_state("Aerodactyl", "Sneasler", "Incineroar", "Aerodactyl", "Aerodactyl")
    opp_aero = s.opp_actives[1]
    assert _partner_can_ohko(s, 0, opp_aero) is False


def test_neutralized_threat_does_not_force_protect():
    """Opposing Aerodactyl OHKOs our Sneasler and outspeeds it, but our Mega
    Aerodactyl is faster and removes it first — so Sneasler should NOT cower
    behind Protect, because the threat is (very likely) gone before it can act.
    (It may attack or pivot; the point is it doesn't Protect.)

    The partner here is Farigiraf (not a Fake Out user), isolating the
    'neutralized threat' principle.  (With a Fake Out lead like Incineroar the
    joint pass now legitimately prefers the safe double-Protect — the remover
    itself could be Fake-Out-flinched — which is why the old Incineroar board no
    longer asserts this; the principle itself is still guarded here and by
    test_opp_neutralized_before_acting_detects_faster_ally_ko.)"""
    best_a, best_b = _run("Aerodactyl", "Sneasler", "Farigiraf", "Aerodactyl", "Aerodactyl")
    # Aero removes the opposing Aerodactyl (slot 1); Sneasler does not Protect.
    assert best_a.target_slot == 1
    assert best_b.move_name not in _PROTECT_MOVES


def test_opp_neutralized_before_acting_detects_faster_ally_ko():
    """True when a faster ally guarantees an OHKO on the threat; False otherwise."""
    # Our Sneasler outspeeds opposing Kingambit and guaranteed-OHKOs it (Close Combat).
    # The item is pinned to a revealed non-berry: an *unrevealed* Kingambit is
    # assumed to hold Chople Berry (51.9% usage), which halves Close Combat and
    # correctly suppresses the guaranteed-OHKO fact (0.7.6 item inference).
    s = _make_state("Aerodactyl", "Sneasler", "Incineroar", "Kingambit", "Aerodactyl")
    s.opp_actives[1].item = "Black Glasses"
    assert _opp_neutralized_before_acting(s, 1, s.opp_actives[1]) is True

    # Nobody guarantees an OHKO on a healthy opposing Aerodactyl before it acts.
    s2 = _make_state("Aerodactyl", "Sneasler", "Incineroar", "Aerodactyl", "Aerodactyl")
    assert _opp_neutralized_before_acting(s2, 1, s2.opp_actives[1]) is False


def test_gale_wings_talonflame_is_never_neutralized():
    """A full-HP Talonflame is assumed Gale Wings: its +1-priority Brave Bird
    lands before our KO move, so it is never 'neutralized before acting' even
    when our faster Mega Aerodactyl is guaranteed to OHKO it — and Venusaur
    therefore Protects rather than attacking into the priority hit (case 1.16)."""
    s = _make_state("Aerodactyl", "Venusaur", "Talonflame", "Garchomp", "Aerodactyl")
    talonflame = s.opp_actives[0]
    # Our Mega Aero does outspeed and guarantee-OHKO Talonflame on raw speed...
    assert _partner_can_ohko(s, 0, talonflame) is True
    # ...but Gale Wings priority means it still gets its hit off first.
    assert _opp_has_attacking_priority(talonflame) is True
    assert _opp_neutralized_before_acting(s, 0, talonflame) is False


def test_ko_before_acting_blocks_undeliverable_kill():
    """Offensive mirror of the speed gate (battle 2620687657): Garchomp is
    outsped by Weavile, which guaranteed-OHKOs it (Ice ×4), and no ally removes
    Weavile first — so Garchomp is KO'd before acting.  Its 'guaranteed OHKO' on
    the partner opponent (Alakazam) must not be credited, so it Protects instead
    of throwing away the attack."""
    s = _make_state("Venusaur", "Garchomp", "Weavile", "Alakazam", "Venusaur")
    # This guard tests the doom-gate mechanic via a slow, OHKO'd Garchomp.  Since
    # 0.8.0 the team runs a Choice Scarf Garchomp (211 spe) that OUTSPEEDS
    # Weavile — which would invalidate the scenario — so we pin a non-Scarf item
    # here to keep Garchomp slow and exercise the mechanic as intended.
    s.my_actives[1].item = "Soft Sand"
    assert _ko_before_acting(s, 1) is True          # Garchomp dies before acting
    assert _ko_before_acting(s, 0) is False         # Venusaur is not guaranteed-OHKO'd
    _best_a, best_b = _run("Venusaur", "Garchomp", "Weavile", "Alakazam", "Venusaur")
    assert best_b.move_name not in {"Stomping Tantrum", "Dragon Claw", "Poison Jab"}  # doomed → no wasted attack


def test_outgoing_damage_credits_ko_on_weakened_opponent():
    """A move that only does ~62% to a full-HP opponent must read as a guaranteed
    OHKO once that opponent is chipped (percentage-tracked) — so the engine
    recognises and finishes a weakened target instead of evaluating vs full HP."""
    from damage import outgoing_damage
    v = find_member("Venusaur")
    st = v.mega_stats or v.stats
    full = outgoing_damage("Venusaur", st, ["Sludge Bomb"], "Alakazam",
                           our_ability=v.ability, our_item=v.item)[0]
    chip = outgoing_damage("Venusaur", st, ["Sludge Bomb"], "Alakazam",
                           our_ability=v.ability, our_item=v.item, opp_hp_percent=41)[0]
    assert not full.is_ohko          # 62% of full HP — not a OHKO
    assert chip.is_ohko              # 62% of full ≈ 151% of a 41% bar — guaranteed KO


def test_ability_type_immunity_zeroes_damage():
    """Ability-based immunities (Levitate→Ground, Dry Skin→Water) zero the move
    so the engine never picks it into an immune target."""
    from damage import outgoing_damage
    v = find_member("Venusaur"); vs = v.mega_stats or v.stats
    ep = outgoing_damage("Venusaur", vs, ["Earth Power"], "Chimecho",
                         our_ability=v.ability, our_item=v.item, opp_ability="Levitate")[0]
    assert ep.damage_avg == 0 and ep.effectiveness == 0   # Levitate → Ground immune
    b = find_member("Basculegion")
    wc = outgoing_damage("Basculegion", b.stats, ["Wave Crash"], "Heliolisk",
                         our_ability=b.ability, our_item=b.item, opp_ability="Dry Skin")[0]
    assert wc.damage_avg == 0                              # Dry Skin → Water immune


def test_opponent_screen_reduces_outgoing_damage():
    """An opponent's Aurora Veil cuts our damage to 2/3 (doubles); crits bypass
    screens, and Light Screen doesn't touch physical damage."""
    from damage import outgoing_damage, screen_modifier
    b = find_member("Basculegion")
    plain = outgoing_damage("Basculegion", b.stats, ["Wave Crash"], "Garchomp",
                            our_ability=b.ability, our_item=b.item)[0]
    veil  = outgoing_damage("Basculegion", b.stats, ["Wave Crash"], "Garchomp",
                            our_ability=b.ability, our_item=b.item,
                            opp_screens={"auroraveil"})[0]
    assert veil.damage_avg == pytest.approx(plain.damage_avg * 2 / 3, rel=0.02)
    assert screen_modifier("Special", {"auroraveil"}, crit=True) == 1.0   # crit bypasses
    assert screen_modifier("Physical", {"lightscreen"}) == 1.0            # wrong category


def test_summary_header_matches_version():
    """The baseline turn1-openings snapshot must be regenerated after a version bump.

    Its header records version.__version__ (the single source of truth); if this
    fails, run
    `.venv\\Scripts\\python.exe tools/gen_snapshot.py --scenario turn1_openings --team baseline`.
    """
    from pathlib import Path
    from version import __version__

    summary = (Path(__file__).resolve().parent.parent
               / "snapshots" / "turn1_openings" / "baseline.md")
    header = summary.read_text(encoding="utf-8").splitlines()[2]  # "Engine vX.Y.Z | ..."
    assert f"Engine v{__version__}" in header, (
        f"baseline.md header {header!r} does not match version v{__version__} — "
        f"regenerate with tools/gen_snapshot.py --scenario turn1_openings --team baseline."
    )


# ═══════════════════════════════════════════════════════════════════════════════
# Auto-discovered snapshot regression — replaces the old hand-maintained per-
# section tables.  Every committed snapshots/<scenario>/<team>.md is parsed and
# the engine must reproduce each cell (move/target exact, weight within ±0.05).
# The snapshot file is now the single source of truth; regenerate it with
# tools/gen_snapshot.py after an *approved* behaviour change (per CLAUDE.md).
# Dropping a new snapshot file in automatically extends coverage.
# ═══════════════════════════════════════════════════════════════════════════════

import re as _re
import pathlib as _pathlib

_SNAP_DIR = _pathlib.Path(__file__).resolve().parent.parent / "snapshots"
_HDR_RE = _re.compile(
    r"^## \d+\. My Lead: \*\*(.+?)\*\* \[A\]  \+  \*\*(.+?)\*\* \[B\]"
    r"(?: \*\(mega: (.+?)\)\*)?\s*$"
)
_ROW_RE = _re.compile(r"^\| \d+\.\d+ \| (.+?) \| (.+?) \| (.+?) \| (.+?) \|\s*$")
_DEC_RE = _re.compile(r"^(.*?) `([\d.]+)`$")


def _split_dec(raw: str):
    """'Dual Wingbeat → Sneasler `28.48`' -> ('Dual Wingbeat → Sneasler', 28.48)."""
    m = _DEC_RE.match(raw.strip())
    return m.group(1).strip(), float(m.group(2))


def _load_snapshot_cells():
    """Parse every committed snapshot into per-cell expectations.

    Yields (team_label, our_a, our_b, mega, opp_a, opp_b, dec_a, wt_a, dec_b, wt_b).
    *team_label* is the file stem ('baseline' or 'name@vN') and selects the team.
    """
    cells = []
    for md in sorted(_SNAP_DIR.glob("*/*.md")):
        team_label = md.stem
        our_a = our_b = mega = None
        for line in md.read_text(encoding="utf-8").splitlines():
            h = _HDR_RE.match(line)
            if h:
                our_a, our_b, mega = h.group(1), h.group(2), h.group(3)
                continue
            r = _ROW_RE.match(line)
            if r and our_a:
                opp_a, opp_b, raw_a, raw_b = r.groups()
                dec_a, wt_a = _split_dec(raw_a)
                dec_b, wt_b = _split_dec(raw_b)
                cells.append((team_label, our_a, our_b, mega,
                              opp_a, opp_b, dec_a, wt_a, dec_b, wt_b))
    return cells


_SNAPSHOT_CELLS = _load_snapshot_cells()


@pytest.mark.parametrize(
    "team_label,our_a,our_b,mega,opp_a,opp_b,dec_a,wt_a,dec_b,wt_b",
    _SNAPSHOT_CELLS,
    ids=[f"{c[0]}:{c[1]}+{c[2]}({c[3] or '-'})|{c[4]}+{c[5]}" for c in _SNAPSHOT_CELLS],
)
def test_snapshot_cell(team_label, our_a, our_b, mega, opp_a, opp_b,
                       dec_a, wt_a, dec_b, wt_b):
    """The engine must reproduce each committed snapshot cell."""
    _team.set_active_team(None if team_label == "baseline" else team_label)
    best_a, best_b = _run(our_a, our_b, opp_a, opp_b, mega)
    _chk(best_a, dec_a, opp_a, opp_b, wt_a)
    _chk(best_b, dec_b, opp_a, opp_b, wt_b)


def test_snapshot_parse_is_not_empty():
    """Guard against a silently-empty parse (format drift breaking the regex):
    the baseline snapshot alone must contribute its full 6×20 = 120-cell grid,
    else test_snapshot_cell would vacuously pass with zero cases."""
    assert len(_SNAPSHOT_CELLS) >= 120
