"""tools/seed_supplement_from_logs.py — seed prelim usage data into
data/sets_supplement.json from recorded battle logs.

Mines Battle Data/**/*.json for opponent observations and seeds, for species the
main Reg M-A sets file lacks (the new Reg M-B mons):

  * moves     — from revealed `opp[].mv`, merged by BASE species (a movepool is
                the same pre/post-mega) and written to every observed gap forme.
  * teammates — from the recorded `preview` team sheet (co-occurrence).

Guards (so a sparse/misleading sample can't make a threat look harmless):
  * only seed a species seen in >= MIN_GAMES battles, AND
  * only when at least one DAMAGING move was observed (keeps incoming_damage
    non-empty — otherwise the species stays on the safe synthetic-STAB fallback).

NOT seeded: items / abilities / spreads — the logs don't record them.  Speed can
be recovered from observed turn order once tailwind + boosts are logged (0.13.0);
that is a separate follow-up (see BACKLOG).

Run (from repo root):  .venv\\Scripts\\python.exe tools/seed_supplement_from_logs.py
"""
import sys, os, json, glob
from collections import defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
from data import move_category, move_power
from data.sets import get_sets

MIN_GAMES = 3       # don't commit to a moveset from fewer observations
MAX_TEAMMATES = 10  # cap the teammate list like the main usage file


def base_key(sp: str) -> str:
    for suf in ("-Mega-X", "-Mega-Y", "-Mega"):
        if sp.endswith(suf):
            return sp[:-len(suf)]
    return sp


def _has_damage(moves) -> bool:
    return any(move_category(m) in ("Physical", "Special") or (move_power(m) or 0) > 0
               for m in moves)


def main() -> None:
    base_battles = defaultdict(int)
    base_move_battles = defaultdict(lambda: defaultdict(int))
    formes_seen = defaultdict(set)
    prev_count = defaultdict(int)                       # preview appearances
    co = defaultdict(lambda: defaultdict(int))          # teammate co-occurrence

    for path in glob.glob(os.path.join(ROOT, "Battle Data", "*", "**", "*.json"),
                          recursive=True):
        try:
            b = json.load(open(path, encoding="utf-8"))
        except Exception:
            continue
        # moves (observed in battle, merged by base species)
        moves_this, bases_this = defaultdict(set), set()
        for turn in b.get("turns", []):
            for o in turn.get("opp", []) or []:
                sp = o.get("s")
                if not sp:
                    continue
                k = base_key(sp)
                bases_this.add(k)
                formes_seen[k].add(sp)
                for mv in o.get("mv", []) or []:
                    moves_this[k].add(mv)
        for k in bases_this:
            base_battles[k] += 1
        for k, moves in moves_this.items():
            for mv in moves:
                base_move_battles[k][mv] += 1
        # teammates (from the recorded preview team sheet)
        prev = b.get("preview", {}).get("opp", []) or []
        prev = sorted(set(prev))
        for sp in prev:
            prev_count[sp] += 1
            for other in prev:
                if other != sp:
                    co[sp][other] += 1

    seeded, skipped = {}, []
    for k, n in base_battles.items():
        mv = base_move_battles[k]
        if not mv:
            continue
        moves_pct = {m: round(100.0 * c / n, 1)
                     for m, c in sorted(mv.items(), key=lambda kv: -kv[1])}
        ok = n >= MIN_GAMES and _has_damage(moves_pct)
        for forme in sorted(formes_seen[k]):
            if get_sets(forme) is not None:             # gap-fill only
                continue
            if not ok:
                skipped.append((forme, n))
                continue
            entry = {"raw_count": n, "moves": dict(moves_pct)}
            bk = base_key(forme)
            if prev_count.get(bk):
                tm = {t: round(100.0 * c / prev_count[bk], 1)
                      for t, c in sorted(co[bk].items(), key=lambda kv: -kv[1])[:MAX_TEAMMATES]}
                if tm:
                    entry["teammates"] = tm
            seeded[forme] = entry

    supp = os.path.join(ROOT, "data", "sets_supplement.json")
    doc = json.load(open(supp, encoding="utf-8"))
    # Refresh: drop previously log-seeded entries, keep documentation + any
    # hand-entered species not produced by this tool.
    prev_seeded = set(doc.pop("_seeded", []))
    for sp in list(doc):
        if sp in prev_seeded:
            doc.pop(sp, None)
    doc["_provenance"] = ("Entries listed in _seeded were generated by "
                          "tools/seed_supplement_from_logs.py from battle-log "
                          "observations (moves + teammates only; low-confidence). "
                          "Re-run to refresh; replace with real Smogon M-B usage "
                          "when available.")
    for sp, entry in sorted(seeded.items(), key=lambda kv: -kv[1]["raw_count"]):
        doc[sp] = entry
    doc["_seeded"] = sorted(seeded)
    json.dump(doc, open(supp, "w", encoding="utf-8"), indent=2, ensure_ascii=False)
    open(supp, "a", encoding="utf-8").write("\n")

    print(f"seeded {len(seeded)} forme entries (moves + teammates):\n")
    for sp, e in sorted(seeded.items(), key=lambda kv: -kv[1]["raw_count"]):
        mv = ", ".join(f"{m} {p:.0f}%" for m, p in list(e["moves"].items())[:4])
        tm = ", ".join(e.get("teammates", {}).keys())
        print(f"  {sp:20s} n={e['raw_count']:2d}  moves[{mv}]")
        if tm:
            print(f"  {'':20s}        teammates[{tm}]")
    print(f"\nskipped {len(set(s for s, _ in skipped))} sparse species (kept synthetic fallback)")


if __name__ == "__main__":
    main()
